version: "3.8"
        #local(onde acessaremos com nossa maquina):container
services:
  app:
    build:
      context: ./
    container_name: app-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-php

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

networks:
  app-php:
    driver: bridge